os:
  - linux
  - osx

language: generic

virtualenv:
  system_site_packages: true

sudo: required

dist: trusty

osx_image: xcode7.3

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - distro/travis/before_install.sh

install: true

script:
 - distro/travis/build_and_test.sh

after_failure:
  - echo 'after_failure'

after_success:
  - distro/travis/after_success.sh
